
path: '/content/gdrive/My Drive/Digit Recognition/data' #dataset root dir
train: images/train #training images
val: images/val #val images

names:
    0: display
    1: 1
    2: 2
    3: 3
    4: 4
    5: 5
    6: 6
    7: 7
    8: 8
    9: 9
    10: 0
